### ISSUE TITLE
Soft deprecate Genesis Simple Edits

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-simple-edits#24]
This plugin is a good candidate for soft deprecation. We could add a notice to the readme and suggest alternatives.

- Genesis 3.1+ includes a footer text option at Theme Settings -> Footer.
- Genesis 3.2+ includes an entry meta option at Theme Settings -> Singular Content.
- Users who want to replace their whole footer will need to use a code snippet.

An example of a deprecation notice: https://github.com/studiopress/genesis-simple-faq/pull/63

The goal is to reduce the maintenance overhead for plugins that have good alternatives or are not in popular use.

@dreamwhisper suggested that we may benefit from a public support page documenting the above alternatives, instead of trying to compress the alternatives and code snippet into the plugin header and readme. cc @susannelson for info and any thoughts on this.

We don't currently have a timeline for deprecation, and this plugin still has [over 100k active installations](https://wordpress.org/plugins/genesis-simple-edits/).

**Comment by susannelson** [comment]
Yes, a public facing support page that lists the alternatives works for me.

**Comment by susannelson** [comment]
The new public facing article has been published: https://my.studiopress.com/documentation/usage/genesis-features/edit-the-entry-meta-and-footer-text-with-genesis/
